language: python


python:
  - "3.7"


install:
  - pip install -r requirements.txt
  - pip install -r doc/requirements.txt
  - pip install .


jobs:
  include:
    - stage: run_notebooks
      script:
        - pytest --nbsmoke-run examples/*.ipynb

    - stage: build_docs
      script:
        - nbsite generate-rst --org SystemsGenetics --project-name GemProspector
        - nbsite build --what=html --output=builtdocs
