branches:
  only:
    - master

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  - GSFORGE_DEMO_DATA="${HOME}/GSForge_demo_data"

language: python

services:
  - docker

python:
  - "3.7"

stages:
  - build_dockerfiles
  - test_and_build_docs

install:
  - sudo apt-get install graphviz
  - pip install -r requirements.txt
  - pip install -r doc/requirements.txt
  - pip install .
  - pip install osfclient

jobs:
  include:
    - stage: build_dockerfiles
      install: skip
      script:
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push systemsgenetics/gsforge_interactive:latest
        - docker push systemsgenetics/gsforge_workflow:latest

    - stage: test_and_build_docs
      script:
        - osf -p 6ceuk clone "$GSFORGE_DEMO_DATA"
        - pytest --nbsmoke-run examples/**/*.ipynb
        - nbsite_generate_modules.py GSForge -d ./doc/Reference_Manual -n GSForge
        - nbsite generate-rst --org SystemsGenetics --project-name GSForge --skip AnnotatedGEM
        - nbsite build --what=html --output=builtdocs
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: ./builtdocs
          target_branch: gh-pages
          github_token: $GITHUB_TOKEN
          on:
            branch: master
