#
# This file triggers a travis-ci build upon a commit to the master branch.
#
# The travis.yml file (in that branch) controls how travis will handle builds.

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  - GSFORGE_DEMO_DATA="${HOME}/GSForge_demo_data"


#cache:
#  directories:
#    - "$GSFORGE_DEMO_DATA"
#    - "$GSFORGE_DEMO_DATA/boruta_gene_sets/"

language: python

services:
  - docker

python:
  - "3.7"


stages:
#  - name: Update OSF files
#    if: commit_message =~ \bupdate_osf\b
  - build_dockerfiles
  - test_and_build_docs


install:
  - wget http://download.asperasoft.com/download/sw/ascp-client/3.5.4/ascp-install-3.5.4.102989-linux-64.sh
  - sudo sh ./ascp-install-3.5.4.102989-linux-64.sh
  - pip install -r requirements.txt
  - pip install -r doc/requirements.txt
  - pip install .
  - pip install osfclient

jobs:
  include:
#    - stage: Update OSF files
#      install: skip
#      script:
#        - pip install osfclient
#        - osf -p 6ceuk clone ${GSFORGE_DEMO_DATA}

    - stage: build_dockerfiles
      install: skip
      script:
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push systemsgenetics/gsforge_interactive:latest
        - docker push systemsgenetics/gsforge_workflow:latest

    - stage: test_and_build_docs
      script:
        - osf -p 6ceuk clone "$GSFORGE_DEMO_DATA"
#        - ls "$GSFORGE_DEMO_DATA"
        - pytest --nbsmoke-run examples/*.ipynb
        - nbsite_generate_modules.py GSForge -d ./doc/Reference_Manual -n GSForge
        - nbsite generate-rst --org SystemsGenetics --project-name GSForge
        - nbsite build --what=html --output=builtdocs
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: ./builtdocs
          target_branch: gh-pages
          github_token: $GITHUB_TOKEN
          on:
            branch: master
