language: python

services:
  - docker

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev


python:
  - "3.7"


install:
  - pip install -r requirements.txt
  - pip install -r doc/requirements.txt
  - pip install .

before_script:
  - mkdir ~/data
  - "curl -X 'GET' \"https://files.osf.io/v1/resources/rbhfz/providers/osfstorage/5da74c9a26eb50000d827679?action=download&amp;version=1&amp;direct\" -H \"Authorization: Bearer ${OSF_TOKEN}\" --output ~/data/osativa.nc"

jobs:
  include:
    - stage: run_notebooks
      script:
        - pytest --nbsmoke-run examples/*.ipynb

    - stage: build_docs
      script:
        - nbsite generate-rst --org SystemsGenetics --project-name GEMprospector
        - nbsite build --what=html --output=builtdocs
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: ./builtdocs
          target_branch: gh-pages
          github_token: $GITHUB_TOKEN
          on:
            branch: master