branches:
  only:
  - master

language: python

services:
  - docker

python:
  - "3.7"


install:
  - pip install -r requirements.txt
  - pip install -r doc/requirements.txt
  - pip install .


jobs:
  include:
    - stage: build_dockerfiles
      install: skip
      script:
        - docker build -t systemsgenetics/gemprospector_interactive:latest .
        - docker build -t systemsgenetics/gemprospector_workflow:latest workflows/
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push systemsgenetics/gemprospector_interactive:latest
        - docker push systemsgenetics/gemprospector_workflow:latest

    - stage: stage demo data
      script: "curl -X 'GET' \"https://files.osf.io/v1/resources/rbhfz/providers/osfstorage/5da74c9a26eb50000d827679?action=download&amp;version=1&amp;direct\" -H \"Authorization: Bearer ${OSF_TOKEN}\" --output ~/data/osativa.nc"


    - stage: test_and_build_docs
      script:
        - mkdir ~/data
        - "curl -X 'GET' \"https://files.osf.io/v1/resources/rbhfz/providers/osfstorage/5da74c9a26eb50000d827679?action=download&amp;version=1&amp;direct\" -H \"Authorization: Bearer ${OSF_TOKEN}\" --output ~/data/osativa.nc"
        - pytest --nbsmoke-run examples/*.ipynb
        - nbsite generate-rst --org SystemsGenetics --project-name GEMprospector
        - nbsite build --what=html --output=builtdocs
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: ./builtdocs
          target_branch: gh-pages
          github_token: $GITHUB_TOKEN
          on:
            branch: master