branches:
  only:
    - master

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  - GSFORGE_DEMO_DATA="${HOME}/GSForge_demo_data"

language: python

services:
  - docker

python:
  - "3.7"

stages:
  - test_and_build_docs
  - build_dockerfiles

install:
  - sudo apt-get install graphviz
  - pip install -r requirements.txt
  - pip install -r doc/requirements.txt
  - pip install .
  - pip install osfclient

jobs:
  include:
    - stage: test_and_build_docs
      script:
        - osf -p rbhfz clone "$GSFORGE_DEMO_DATA"
#        - pytest --nbsmoke-run examples/user_guide/AnnotatedGEM_from_pandas.ipynb
        - nbsite_generate_modules.py GSForge -d ./doc/Reference_Manual -n GSForge
        # The pipe below enables use of a multiple line bash script.
        - |
          nbsite generate-rst --org SystemsGenetics --project-name GSForge \
          --skip="[^.*R_integration_guide.*ipynb]"
        - nbsite build --what=html --output=builtdocs
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: ./builtdocs
          target_branch: gh-pages
          github_token: $GITHUB_TOKEN
          on:
            branch: master

    - stage: build_dockerfiles
      install: skip
      script:
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push systemsgenetics/gsforge_interactive:latest
        - docker push systemsgenetics/gsforge_workflow:latest