language: python


python:
  - "3.7"


install:
  - pip install -r requirements.txt
  - pip install -r doc/requirements.txt
  - pip install .


script:
  - pytest --nbsmoke-lint examples/*.ipynb
  - pytest --nbsmoke-run examples/*.ipynb
