#
# This file triggers a travis-ci build upon a commit to the master branch.
#
# The travis.yml file (in that branch) controls how travis will handle builds.
#
#

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  - GEMPROSPECTOR_DATA="${HOME}/GEMprospector_demo_data"


cache:
  directories:
    - $GEMPROSPECTOR_DATA
    - $GEMPROSPECTOR_DATA/lineaments/

language: python

services:
  - docker

python:
  - "3.7"


stages:
  - name: Update OSF files
    if: commit_message =~ \bupdate_osf\b
  - build_dockerfiles
  - test_and_build_docs


install:
  - pip install -r requirements.txt
  - pip install -r doc/requirements.txt
  - pip install .


jobs:
  include:

    - stage: Update OSF files
      install: skip
      script:
        - rm -rf ${GEMPROSPECTOR_DATA}
        - mkdir -p ${GEMPROSPECTOR_DATA}/lineaments/
        - "curl -X 'GET' \"https://files.osf.io/v1/resources/rbhfz/providers/osfstorage/5db1eba3365cb8000dd9d251?action=download&amp;version=1&amp;direct\" -H \"Authorization: Bearer ${OSF_TOKEN}\" --output ${GEMPROSPECTOR_DATA}/rice_heat_drought.GEM.raw.txt"
        - "curl -X 'GET' \"https://files.osf.io/v1/resources/rbhfz/providers/osfstorage/5db1ebb6365cb8000ad9194e?action=download&amp;version=1&amp;direct\" -H \"Authorization: Bearer ${OSF_TOKEN}\" --output ${GEMPROSPECTOR_DATA}/srx_sample_annots.txt"
        - "curl -X 'GET' \"https://files.osf.io/v1/resources/rbhfz/providers/osfstorage/5db1ebd0365cb8000dd9d28d?action=download&amp;version=1&amp;direct\" -H \"Authorization: Bearer ${OSF_TOKEN}\" --output ${GEMPROSPECTOR_DATA}/all.gff3"
        - "curl -X 'GET' \"https://files.osf.io/v1/resources/rbhfz/providers/osfstorage/5db1f74f0db187000c3ab77d?action=download&amp;version=1&amp;direct\" -H \"Authorization: Bearer ${OSF_TOKEN}\" --output ${GEMPROSPECTOR_DATA}/osativa.nc"
        - "curl -X 'GET' \"https://files.osf.io/v1/resources/rbhfz/providers/osfstorage/5db37d30af84c3000ee17d09?action=download&amp;version=1&amp;direct\" -H \"Authorization: Bearer ${OSF_TOKEN}\" --output ${GEMPROSPECTOR_DATA}/lineaments/Genotype.nc"
        - "curl -X 'GET' \"https://files.osf.io/v1/resources/rbhfz/providers/osfstorage/5db37d30f3bb87000d82888a?action=download&amp;version=2&amp;direct\" -H \"Authorization: Bearer ${OSF_TOKEN}\" --output ${GEMPROSPECTOR_DATA}/lineaments/Subspecies.nc"
        - "curl -X 'GET' \"https://files.osf.io/v1/resources/rbhfz/providers/osfstorage/5db37d2ecfc96c000ebb6b20?action=download&amp;version=1&amp;direct\" -H \"Authorization: Bearer ${OSF_TOKEN}\" --output ${GEMPROSPECTOR_DATA}/lineaments/Treatment.nc"

    - stage: build_dockerfiles
      install: skip
      script:
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push systemsgenetics/gemprospector_interactive:latest
        - docker push systemsgenetics/gemprospector_workflow:latest

    - stage: test_and_build_docs
      script:
        - pytest --nbsmoke-run examples/*.ipynb
        - nbsite_generate_modules.py GEMprospector -d ./Reference_Manual -n GEMprospector
        - nbsite generate-rst --org SystemsGenetics --project-name GEMprospector
        - nbsite build --what=html --output=builtdocs
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: ./builtdocs
          target_branch: gh-pages
          github_token: $GITHUB_TOKEN
          on:
            branch: master
